### ISSUE TITLE
git-notes

### ISSUE THREAD

**Issue by MuzheZeng** [MuzheZeng/992-Comp-Tool-for-Data-Analytics#1]
@cecileane @arhenry2
This is my new repository for lecture notes.

**Comment by cecileane** [comment]
Very nice use of markdown, Muzhe.

Anything that was new and stood out? If nothing was new for you, what do you recommend for the course (go faster, provide more/fewer exercises, etc.)?

**Comment by MuzheZeng** [comment]
I used Rmarkdown before so it looks similar to me. Certainly I still learn sth from it. Looking forward to new stuff from class!

**Comment by cecileane** [comment]
thanks!
